language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
  pip: true
  directories:
  - "~/.platformio"
  - "./.pioenvs"

env:
    - LINUX_SRC=linux
    - PLATFORMIO_CI_SRC=features/Radio/radio
    - PLATFORMIO_CI_SRC=features/Profile/profile

install:
    - pip install -U platformio
    - platformio update

script:
  - platformio ci features/ --board=esp32dev --lib="."
