language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
  pip: true
  directories:
  - "~/.platformio"
  - "./.pioenvs"

install:
    - pip install -U platformio
    - pip install -U cpplint
    - platformio update

script:
  - cpplint --quiet --recursive lib --recursive src
  - platformio run -s
  - mkdir build && cd build && cmake .. && make && make test
