@startuml

title EAP - Component Diagram

[instructor]
[pumpcommunication] -- resultCommunication
[pumpcommunication] -- commandCommunication
[monitoring] - monitor
[prediction] - predict


[monitoring] --> resultCommunication
[prediction] --> monitor
[instructor] --> predict
[instructor] --> commandCommunication

@enduml
