@startuml

title EAP - Component Diagram

[pumpcommunication] -- communication
[pumpcommunication] - pumpconfiguration
[carelinktranslation] - carelink
[monitoring] - monitor
[prediction] - predict
[controlling] - control

[carelinktranslation] --> communication
[monitoring] --> carelink
[prediction] --> monitor
[controlling] --> predict
[controlling] --> carelink


@enduml
