@startuml

set namespaceSeparator ::

title EAP - PumpCommunication

namespace communication {

class PumpCommunication {
  + PumpCommunication(config: PumpConfiguration, radio: RadioInterface)
  + init(): int
  + send(packet: const Packet): int
  + receive(Packet* packet): int
  - radio: Radio
}

class Packet {
  - data: byte[]
  + Packet(size: int, data: byte[])
  + getData(): byte[]
  + validate(): int
}

class PumpConfiguration {
  + frequency: int
}

namespace radio {
interface RadioInterface {
  + send(packet: Packet)
  + receive(Packet& packet): int
}

class Radio {
  + Radio(configuration: PumpConfiguration)
  + send(packet: Packet): int
  + receive(Packet& packet): int
  - timeout: int
  - retries: int
}
}

namespace validation {
class CRC {
  {static} + CRC8WCDMA(data: byte[], count: unsigned int): uint8_t
  {static} - reflect(input: uint8_t): uint8_t
  {static} - crcTable : byte[]
}
}

Packet -> communication::validation::CRC
communication::radio::Radio o-- PumpConfiguration
communication::radio::Radio -|> communication::radio::RadioInterface
communication::radio::RadioInterface o-- Packet
PumpCommunication *- communication::radio::RadioInterface
PumpCommunication o- Packet

}
@enduml

